apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rule-engine.configmapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rule-engine.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.engineConfig | toYaml | nindent 4 }}
